# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-20 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clamapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='commented_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clamapp.Profile'),
        ),
        migrations.AddField(
            model_name='comments',
            name='commented_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clamapp.Image'),
        ),
    ]
